 - name: key_block_for_new_ubuntu
   block: 
     - name: create_keyrings_dir
       file:
         path: /etc/apt/keyrings
         state: directory
         mode: "0755"

     - name: get_key
       shell: |
             curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
       args: 
         creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg # чтоб не дописывал раз за разом
       become: yes

     - name: key_install
       shell: |
              echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
       args:
          creates: /etc/apt/sources.list.d/kubernetes.list
       become: yes

 - name: apt_install
   block:
     - name: kuber_install
       apt:
         name:
          - vim
          - kubelet
          - kubeadm
          - kubectl
          - conntrack
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common
         state: present
         update_cache: yes

     - name: apt_hold_version
       shell: |
               sudo apt-mark hold kubelet kubeadm kubectl
       become: yes

 - name: server_prepare
   block:
    - name: ip_forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        sysctl_set: yes # применит сразу в /proc , потом проверить
   
    - name: modules_to_core # просто через эхо не вариант из-за повторений
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        create: yes
        mode: '0644'
      loop: 
          - overlay
          - br_netfilter

    - name: load_modules # загрузим модули
      ansible.builtin.command: modprobe "{{ item }}"
      loop: 
       - overlay
       - br_netfilter
         #  listen: reload modules # проверим оповещение

    - name: containerd_get_key
      shell: |
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args: 
        creates: /etc/apt/keyrings/docker.gpg
      become: yes

    - name: add_docker_repository_for_containerd
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable"
        state: present
        filename: docker

    - name: install_containerd
      apt:
        name:
          - containerd.io
          - docker-ce-cli  # crictl для работы с контейнерами может понадобиться
        state: present
        update_cache: yes

    - name: generate_default_containerd_config
      shell: containerd config default > /etc/containerd/config.toml
      #args:
      # creates: /etc/containerd/config.toml # конфиг есть по умолчанию, и он не канает, так что зависимость убираем, чтоб таск отработал
      become: yes

    - name: enable_config_parametr
      shell: |
              sed -i 's#SystemdCgroup = false#SystemdCgroup = true#g' /etc/containerd/config.toml &&
              sudo systemctl restart containerd &&
              sudo systemctl enable containerd --now
      become: yes
